In [2]:
import pandas as pd
import numpy as np
import pickle
career = pd.read_csv('dataset_skills.csv', header = None)

In [3]:
career.head()

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0   5   5   5   5   1   5   9   5   5   5   5   5   5   5   5   5   5   
1   6   6   6   6   6   6   6   6   6   9   6   6   6   6   2   6   6   
2   6   5   6   6   6   9   6   6   6   6   6   6   6   6   6   6   6   
3   9   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   2   
4   2   2   2   2   2   2   2   2   2   2   2   5   2   2   2   9   2   

                       17  
0          API Specialist  
1        Technical Writer  
2      Software Developer  
3  Database Administrator  
4       Helpdesk Engineer

In [4]:
X = np.array(career.iloc[:, 0:17]) #X is skills
print(X)
y = np.array(career.iloc[:, 17]) #Y is Roles
print("hi")
print(y) 

[[5 5 5 ... 5 5 5]
 [6 6 6 ... 2 6 6]
 [6 5 6 ... 6 6 6]
 ...
 [9 7 7 ... 7 5 5]
 [6 6 9 ... 6 6 6]
 [2 2 2 ... 2 2 9]]
hi
['API Specialist' 'Technical Writer' 'Software Developer' ...
 'Database Administrator' 'Application Support Engineer'
 'Graphics Designer']


In [5]:
career.columns = ["Database Fundamentals","Computer Architecture","Distributed Computing Systems",
"Cyber Security","Networking","Development","Programming Skills","Project Management",
"Computer Forensics Fundamentals","Technical Communication","AI ML","Software Engineering","Business Analysis",
"Communication skills","Data Science","Troubleshooting skills","Graphics Designing","Roles"]

career.dropna(how ='all', inplace = True)

In [6]:
career.head()

Database Fundamentals  Computer Architecture  \
0                      5                      5   
1                      6                      6   
2                      6                      5   
3                      9                      2   
4                      2                      2   

   Distributed Computing Systems  Cyber Security  Networking  Development  \
0                              5               5           1            5   
1                              6               6           6            6   
2                              6               6           6            9   
3                              2               2           2            2   
4                              2               2           2            2   

   Programming Skills  Project Management  Computer Forensics Fundamentals  \
0                   9                   5                                5   
1                   6                   6                                6   
2                   6                   6                                6   
3                   2                   2                                2   
4                   2                   2                                2   

   Technical Communication  AI ML  Software Engineering  Business Analysis  \
0                        5      5                     5                  5   
1                        9      6                     6                  6   
2                        6      6                     6                  6   
3                        2      2                     2                  2   
4                        2      2                     5                  2   

   Communication skills  Data Science  Troubleshooting skills  \
0                     5             5                       5   
1                     6             2                       6   
2                     6             6                       6   
3                     2             2                       2   
4                     2             2                       9   

   Graphics Designing                   Roles  
0                   5          API Specialist  
1                   6        Technical Writer  
2                   6      Software Developer  
3                   2  Database Administrator  
4                   2       Helpdesk Engineer

In [7]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state = 524)
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
scores = {}
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)
print('X_train',X_train)
print('y_train',y_train)
y_pred = knn.predict(X_test)
print('y_pred',y_pred)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

pickle.dump(knn, open('knn_model.pkl','wb'))
print('test file created')

X_train [[5 5 5 ... 5 5 5]
 [7 7 7 ... 7 7 7]
 [1 1 1 ... 1 1 1]
 ...
 [6 6 6 ... 6 6 6]
 [3 3 3 ... 3 1 1]
 [6 6 6 ... 6 6 6]]
y_train ['Software Developer' 'Business Analyst' 'Cyber Security Specialist' ...
 'Cyber Security Specialist' 'Cyber Security Specialist'
 'Information Security Specialist']
y_pred ['Software tester' 'Networking Engineer' 'Networking Engineer' ...
 'Cyber Security Specialist' 'Software Developer' 'Business Analyst']
0.970679012345679
test file created


C:\Users\Nikshith\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
